=== ernadosmic/brcko_bus/assets/schedules/bus_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Bus Schedule",
    "type": "object",
    "required": [
        "name",
        "line_number",
        "services",
        "regular_services",
        "irregular_services",
        "regular_explanation",
        "irregular_explanation",
        "stops"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "line_number": {
            "type": "string"
        },
        "services": {
            "type": "integer",
            "minimum": 1
        },
        "regular_services": {
            "type": "array",
            "items": {
                "type": "integer"
            }
        },
        "irregular_services": {
            "type": "array",
            "items": {
                "type": "integer"
            }
        },
        "regular_explanation": {
            "type": "string"
        },
        "irregular_explanation": {
            "type": "string"
        },
        "stops": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "times"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "times": {
                        "type": "array",
                        "minItems": 18,
                        "maxItems": 18,
                        "items": {
                            "type": "string",
                            "pattern": "^\\d{2}:\\d{2}$"
                        }
                    }
                }
            }
        }
    }
}

=== ernadosmic/brcko_bus/assets/schedules/line_11B.json
{
    "$schema": "./bus_schema.json",
    "name": "Tesla - Bukvik Škola (povratak)",
    "line_number": "11B",
    "services": 4,
    "regular_services": [
        5,
        6,
        7,
        8
    ],
    "irregular_services": [],
    "regular_explanation": "Polasci pod brojevima 5, 6, 7, 8 saobraćaju svakodnevno",
    "irregular_explanation": "",
    "stops": [
        {
            "name": "TESLA",
            "times": [
                "06:28",
                "07:39",
                "14:39",
                "20:39"
            ]
        },
        {
            "name": "Vet. Stanica",
            "times": [
                "06:27",
                "07:38",
                "14:38",
                "20:38"
            ]
        },
        {
            "name": "Centar",
            "times": [
                "06:24",
                "07:35",
                "14:35",
                "20:35"
            ]
        },
        {
            "name": "Kolobara",
            "times": [
                "06:23",
                "07:34",
                "14:34",
                "20:34"
            ]
        },
        {
            "name": "Dom Zdravlja",
            "times": [
                "06:22",
                "07:33",
                "14:33",
                "20:33"
            ]
        },
        {
            "name": "Meraje",
            "times": [
                "06:21",
                "07:32",
                "14:32",
                "20:32"
            ]
        },
        {
            "name": "Izbor",
            "times": [
                "06:20",
                "07:31",
                "14:31",
                "20:31"
            ]
        },
        {
            "name": "Broduša",
            "times": [
                "06:19",
                "07:30",
                "14:30",
                "20:30"
            ]
        },
        {
            "name": "Suljagića Sokak",
            "times": [
                "06:18",
                "07:29",
                "14:29",
                "20:29"
            ]
        },
        {
            "name": "Stari Rasanidik",
            "times": [
                "06:16",
                "07:27",
                "14:27",
                "20:27"
            ]
        },
        {
            "name": "Brod Škola",
            "times": [
                "06:13",
                "07:24",
                "14:24",
                "20:24"
            ]
        },
        {
            "name": "Ulović Groblje",
            "times": [
                "06:14",
                "07:17",
                "14:17",
                "20:17"
            ]
        },
        {
            "name": "Ulović Crkva",
            "times": [
                "06:12",
                "07:15",
                "14:15",
                "20:15"
            ]
        },
        {
            "name": "Radoševci",
            "times": [
                "06:10",
                "07:12",
                "14:12",
                "20:12"
            ]
        },
        {
            "name": "Bukovac Ž.St.",
            "times": [
                "06:09",
                "07:11",
                "14:11",
                "20:11"
            ]
        },
        {
            "name": "Bukovac Crkva",
            "times": [
                "05:57",
                "07:08",
                "14:08",
                "20:08"
            ]
        },
        {
            "name": "Vitanovići",
            "times": [
                "05:56",
                "07:07",
                "14:07",
                "20:07"
            ]
        },
        {
            "name": "Vitanovići Dom",
            "times": [
                "05:55",
                "07:06",
                "14:06",
                "20:06"
            ]
        },
        {
            "name": "Bukvik Škola",
            "times": [
                "05:54",
                "07:05",
                "14:05",
                "20:05"
            ]
        }
    ]
}

=== ernadosmic/brcko_bus/assets/schedules/line_3A.json
{
    "$schema": "./bus_schema.json",
    "name": "Posavci - Bolnica",
    "line_number": "3",
    "services": 5,
    "regular_services": [
        1,
        3,
        4,
        5
    ],
    "irregular_services": [
        2
    ],
    "regular_explanation": "Polasci pod brojevima 1, 3, 4, 5 saobraćaju svakodnevno",
    "irregular_explanation": "Polasci pod brojem 2 ne saobraćaju subotom, nedjeljom i praznikom",
    "stops": [
        {
            "name": "POSAVCI",
            "times": [
                "05:40",
                "07:10",
                "11:40",
                "14:20",
                "16:30"
            ]
        },
        {
            "name": "Ražljevo",
            "times": [
                "05:45",
                "07:15",
                "11:45",
                "14:25",
                "16:35"
            ]
        },
        {
            "name": "Popovo p. (R)",
            "times": [
                "05:48",
                "",
                "11:48",
                "14:28",
                ""
            ]
        },
        {
            "name": "Popovo polje",
            "times": [
                "05:50",
                "",
                "11:50",
                "14:30",
                ""
            ]
        },
        {
            "name": "Popovo (R)",
            "times": [
                "05:52",
                "",
                "11:52",
                "14:32",
                ""
            ]
        },
        {
            "name": "Ražljevo",
            "times": [
                "05:55",
                "07:15",
                "11:55",
                "14:35",
                "16:35"
            ]
        },
        {
            "name": "Krbeti",
            "times": [
                "06:00",
                "07:20",
                "12:00",
                "14:40",
                "16:40"
            ]
        },
        {
            "name": "Sandići",
            "times": [
                "06:03",
                "07:23",
                "12:03",
                "14:43",
                "16:43"
            ]
        },
        {
            "name": "Buzekara",
            "times": [
                "06:06",
                "07:26",
                "12:06",
                "14:46",
                "16:46"
            ]
        },
        {
            "name": "Jasika",
            "times": [
                "06:09",
                "07:29",
                "12:09",
                "14:49",
                "16:49"
            ]
        },
        {
            "name": "Stanovi",
            "times": [
                "06:12",
                "07:32",
                "12:12",
                "14:52",
                "16:52"
            ]
        },
        {
            "name": "Takiša",
            "times": [
                "06:17",
                "07:37",
                "12:17",
                "14:57",
                "16:57"
            ]
        },
        {
            "name": "Brezik Dom",
            "times": [
                "06:19",
                "07:39",
                "12:19",
                "14:59",
                "16:59"
            ]
        },
        {
            "name": "Brezik I",
            "times": [
                "06:20",
                "07:40",
                "12:20",
                "15:00",
                "17:00"
            ]
        },
        {
            "name": "Brezik R.",
            "times": [
                "06:21",
                "07:41",
                "12:21",
                "15:01",
                "17:01"
            ]
        },
        {
            "name": "Seljanka(Škola)",
            "times": [
                "06:22",
                "07:42",
                "12:22",
                "15:02",
                "17:02"
            ]
        },
        {
            "name": "Farma",
            "times": [
                "06:23",
                "07:43",
                "12:23",
                "15:03",
                "17:03"
            ]
        },
        {
            "name": "Grčica II",
            "times": [
                "06:24",
                "07:44",
                "12:24",
                "15:04",
                "17:04"
            ]
        },
        {
            "name": "Grčica I (Crkva)",
            "times": [
                "06:25",
                "07:45",
                "12:25",
                "15:05",
                "17:05"
            ]
        },
        {
            "name": "Vet.Stanica",
            "times": [
                "06:26",
                "07:46",
                "12:26",
                "15:06",
                "17:06"
            ]
        },
        {
            "name": "Robna kuća",
            "times": [
                "06:27",
                "07:47",
                "12:27",
                "15:07",
                "17:07"
            ]
        },
        {
            "name": "Kolobara",
            "times": [
                "06:28",
                "07:48",
                "12:28",
                "15:08",
                "17:08"
            ]
        },
        {
            "name": "Dom zdravlja",
            "times": [
                "06:29",
                "07:49",
                "12:29",
                "15:09",
                "17:09"
            ]
        },
        {
            "name": "BOLNICA",
            "times": [
                "06:30",
                "07:50",
                "12:30",
                "15:10",
                "17:10"
            ]
        }
    ]
}

=== ernadosmic/brcko_bus/assets/schedules/line_1A.json
{
    "$schema": "./bus_schema.json",
    "name": "Bolnica - Novo Naselje",
    "line_number": "1",
    "services": 5,
    "regular_services": [
        1,
        2,
        3,
        4,
        5
    ],
    "irregular_services": [],
    "regular_explanation": "Polasci pod brojevima 1,2,3,4,5 saobraćaju svakodnevno",
    "irregular_explanation": "",
    "stops": [
        {
            "name": "Bolnica",
            "times": [
                "06:30",
                "10:25",
                "13:35",
                "16:35",
                "19:25"
            ]
        },
        {
            "name": "Dom Zdravlja",
            "times": [
                "06:31",
                "10:26",
                "13:36",
                "16:36",
                "19:26"
            ]
        },
        {
            "name": "Kolobara",
            "times": [
                "06:32",
                "10:27",
                "13:37",
                "16:37",
                "19:27"
            ]
        },
        {
            "name": "Centar",
            "times": [
                "06:33",
                "10:28",
                "13:38",
                "16:38",
                "19:28"
            ]
        },
        {
            "name": "Šumarija",
            "times": [
                "06:34",
                "10:29",
                "13:39",
                "16:39",
                "19:29"
            ]
        },
        {
            "name": "Uljarica",
            "times": [
                "06:35",
                "10:30",
                "13:40",
                "16:40",
                "19:30"
            ]
        },
        {
            "name": "Bosnaprod",
            "times": [
                "06:36",
                "10:31",
                "13:41",
                "16:41",
                "19:31"
            ]
        },
        {
            "name": "Farma",
            "times": [
                "06:37",
                "10:32",
                "13:42",
                "16:42",
                "19:32"
            ]
        },
        {
            "name": "Blizna",
            "times": [
                "06:38",
                "10:33",
                "13:43",
                "16:43",
                "19:33"
            ]
        },
        {
            "name": "Brezik R.",
            "times": [
                "06:39",
                "10:34",
                "13:44",
                "16:44",
                "19:34"
            ]
        },
        {
            "name": "Stolin",
            "times": [
                "06:40",
                "10:35",
                "13:45",
                "16:45",
                "19:35"
            ]
        },
        {
            "name": "Pirometali",
            "times": [
                "06:41",
                "10:36",
                "13:46",
                "16:46",
                "19:36"
            ]
        },
        {
            "name": "Gredice II (R)",
            "times": [
                "06:43",
                "10:38",
                "13:48",
                "16:48",
                "19:38"
            ]
        },
        {
            "name": "Gredice (R)",
            "times": [
                "06:45",
                "10:40",
                "13:50",
                "16:50",
                "19:40"
            ]
        },
        {
            "name": "Sandići (R)",
            "times": [
                "06:46",
                "10:41",
                "13:51",
                "16:51",
                "19:41"
            ]
        },
        {
            "name": "Trnjaci (R)",
            "times": [
                "06:49",
                "10:44",
                "13:54",
                "16:54",
                "19:44"
            ]
        },
        {
            "name": "S.B. Polje (R)",
            "times": [
                "06:50",
                "10:45",
                "13:55",
                "16:55",
                "19:45"
            ]
        },
        {
            "name": "S.B. Polje igralište",
            "times": [
                "",
                "",
                "",
                "19:46",
                ""
            ]
        },
        {
            "name": "S.B. Polje igralište",
            "times": [
                "",
                "",
                "",
                "19:47",
                ""
            ]
        },
        {
            "name": "S.B. Polje igralište",
            "times": [
                "",
                "",
                "",
                "19:48",
                ""
            ]
        },
        {
            "name": "S.B. Polje (R)",
            "times": [
                "",
                "",
                "",
                "19:49",
                ""
            ]
        },
        {
            "name": "B. Polje",
            "times": [
                "06:55",
                "10:50",
                "14:00",
                "17:00",
                "19:50"
            ]
        },
        {
            "name": "Novo Naselje",
            "times": [
                "06:58",
                "10:53",
                "14:03",
                "17:03",
                "19:53"
            ]
        }
    ]
}

=== ernadosmic/brcko_bus/assets/schedules/line_2A.json
{
    "$schema": "./bus_schema.json",
    "name": "Vučilovac - Marković Polje",
    "line_number": "2",
    "services": 7,
    "regular_services": [
        3,
        6,
        7
    ],
    "irregular_services": [
        1,
        2,
        4,
        5
    ],
    "regular_explanation": "Polasci pod brojem 3, 6, 7 saobraćaju svakodnevno",
    "irregular_explanation": "Polasci pod brojem 1, 2, 4, 5 ne saobraćaju subotom, nedjeljom i praznikom",
    "stops": [
        {
            "name": "VUČILOVAC",
            "times": [
                "05:55",
                "06:04",
                "09:00",
                "—",
                "—",
                "—",
                "—"
            ]
        },
        {
            "name": "Čišva",
            "times": [
                "—",
                "—",
                "09:06",
                "—",
                "—",
                "—",
                "—"
            ]
        },
        {
            "name": "Krepšić Pošta",
            "times": [
                "—",
                "—",
                "09:15",
                "—",
                "—",
                "—",
                "—"
            ]
        },
        {
            "name": "Krepšić Škola",
            "times": [
                "—",
                "—",
                "—",
                "11:05",
                "12:00",
                "14:00",
                "17:30"
            ]
        },
        {
            "name": "M. POLJE",
            "times": [
                "—",
                "07:00",
                "—",
                "11:07",
                "12:02",
                "14:02",
                "17:32"
            ]
        },
        {
            "name": "Krepšić Škola",
            "times": [
                "—",
                "07:02",
                "—",
                "11:08",
                "12:03",
                "14:03",
                "17:33"
            ]
        },
        {
            "name": "Krepšić Pošta",
            "times": [
                "—",
                "07:03",
                "—",
                "—",
                "—",
                "—",
                "—"
            ]
        },
        {
            "name": "Vučilovac-Čišva",
            "times": [
                "—",
                "—",
                "—",
                "—",
                "—",
                "—",
                "—"
            ]
        },
        {
            "name": "Krepšić Pošta",
            "times": [
                "—",
                "—",
                "—",
                "—",
                "—",
                "—",
                "—"
            ]
        },
        {
            "name": "Gorice",
            "times": [
                "06:13",
                "07:06",
                "09:18",
                "11:11",
                "12:06",
                "14:06",
                "17:36"
            ]
        },
        {
            "name": "Timko",
            "times": [
                "06:15",
                "07:08",
                "09:20",
                "11:13",
                "12:08",
                "14:08",
                "17:38"
            ]
        },
        {
            "name": "Slankara",
            "times": [
                "06:18",
                "07:11",
                "09:23",
                "11:16",
                "12:11",
                "14:11",
                "17:41"
            ]
        },
        {
            "name": "Grbavica (R)",
            "times": [
                "06:20",
                "07:13",
                "09:25",
                "11:18",
                "12:13",
                "14:13",
                "17:43"
            ]
        },
        {
            "name": "Ulički put",
            "times": [
                "06:22",
                "07:15",
                "09:27",
                "11:20",
                "12:15",
                "14:15",
                "17:45"
            ]
        },
        {
            "name": "Grbavica škola",
            "times": [
                "—",
                "07:18",
                "—",
                "11:23",
                "12:18",
                "—",
                "—"
            ]
        },
        {
            "name": "Ulički put",
            "times": [
                "—",
                "07:21",
                "—",
                "—",
                "12:21",
                "—",
                "—"
            ]
        },
        {
            "name": "Antunović p.",
            "times": [
                "06:25",
                "07:24",
                "09:30",
                "—",
                "12:24",
                "14:18",
                "17:48"
            ]
        },
        {
            "name": "PSC",
            "times": [
                "06:26",
                "07:25",
                "09:31",
                "—",
                "12:25",
                "14:19",
                "17:49"
            ]
        },
        {
            "name": "Bolnica",
            "times": [
                "06:27",
                "07:26",
                "09:32",
                "—",
                "12:26",
                "14:20",
                "17:50"
            ]
        },
        {
            "name": "D. Zdravlja",
            "times": [
                "06:28",
                "07:27",
                "09:33",
                "—",
                "12:27",
                "14:21",
                "17:51"
            ]
        },
        {
            "name": "Kolobara",
            "times": [
                "06:30",
                "07:29",
                "09:35",
                "—",
                "12:29",
                "14:23",
                "17:53"
            ]
        },
        {
            "name": "Centar",
            "times": [
                "06:32",
                "07:31",
                "09:37",
                "—",
                "12:31",
                "14:25",
                "17:55"
            ]
        },
        {
            "name": "Vet.stanica",
            "times": [
                "—",
                "07:34",
                "09:40",
                "—",
                "12:34",
                "14:28",
                "17:58"
            ]
        },
        {
            "name": "Greica I",
            "times": [
                "—",
                "07:35",
                "09:41",
                "—",
                "12:35",
                "14:29",
                "17:59"
            ]
        },
        {
            "name": "Greica II",
            "times": [
                "—",
                "07:36",
                "09:42",
                "—",
                "12:36",
                "14:30",
                "18:00"
            ]
        },
        {
            "name": "Farma",
            "times": [
                "—",
                "07:37",
                "09:43",
                "—",
                "12:37",
                "14:31",
                "18:01"
            ]
        },
        {
            "name": "Seljanka",
            "times": [
                "—",
                "07:38",
                "09:44",
                "—",
                "12:38",
                "14:32",
                "18:02"
            ]
        },
        {
            "name": "Brezik raskr.",
            "times": [
                "—",
                "07:39",
                "09:45",
                "—",
                "12:39",
                "14:33",
                "18:03"
            ]
        },
        {
            "name": "Brezik crkva",
            "times": [
                "—",
                "07:40",
                "09:46",
                "—",
                "12:40",
                "14:34",
                "18:04"
            ]
        },
        {
            "name": "Potočari I",
            "times": [
                "—",
                "07:41",
                "09:47",
                "—",
                "12:41",
                "14:35",
                "18:05"
            ]
        },
        {
            "name": "POTOČARI II",
            "times": [
                "—",
                "07:43",
                "09:49",
                "—",
                "12:43",
                "14:37",
                "18:07"
            ]
        }
    ]
}
