=== ernadosmic/brcko_bus/assets/schedules/bus_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Bus Schedule",
    "type": "object",
    "required": [
        "name",
        "line_number",
        "services",
        "regular_services",
        "irregular_services",
        "regular_explanation",
        "irregular_explanation",
        "stops"
    ],
    "properties": {
        "name": {
            "type": "string"
        },
        "line_number": {
            "type": "string"
        },
        "services": {
            "type": "integer",
            "minimum": 1
        },
        "regular_services": {
            "type": "array",
            "items": {
                "type": "integer"
            }
        },
        "irregular_services": {
            "type": "array",
            "items": {
                "type": "integer"
            }
        },
        "regular_explanation": {
            "type": "string"
        },
        "irregular_explanation": {
            "type": "string"
        },
        "stops": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "name",
                    "times"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "times": {
                        "type": "array",
                        "minItems": 18,
                        "maxItems": 18,
                        "items": {
                            "type": "string",
                            "pattern": "^\\d{2}:\\d{2}$"
                        }
                    }
                }
            }
        }
    }
}

=== ernadosmic/brcko_bus/assets/schedules/line_9.json
{
    "$schema": "./bus_schema.json",
    "name": "Prutace",
    "line_number": "9",
    "services": 18,
    "regular_services": [
        1,
        3,
        6,
        9,
        13,
        18
    ],
    "irregular_services": [
        2,
        4,
        5,
        7,
        8,
        10,
        11,
        12,
        14,
        15,
        16,
        17
    ],
    "regular_explanation": "Polasci pod brojevima 1,3,6, 9, 13, 18 saobraćaju svakodnevno",
    "irregular_explanation": "Polasci pod brojevima 2,4,5,7,8,10,11,12,14,15,16,17 saobraćaju samo radnim danima",
    "stops": [
        {
            "name": "Maoča Badarka",
            "times": [
                "06:00",
                "06:30",
                "07:00",
                "07:30",
                "08:00",
                "10:00",
                "11:00",
                "11:30",
                "12:00",
                "12:30",
                "13:00",
                "13:30",
                "15:00",
                "16:00",
                "17:30",
                "18:00",
                "19:00",
                "20:00"
            ]
        },
        {
            "name": "Maoča Centar",
            "times": [
                "06:01",
                "06:31",
                "07:01",
                "07:31",
                "08:01",
                "10:01",
                "11:01",
                "11:31",
                "12:01",
                "12:31",
                "13:01",
                "13:31",
                "15:01",
                "16:01",
                "17:31",
                "18:01",
                "19:01",
                "20:01"
            ]
        },
        {
            "name": "govno",
            "times": [
                "06:00",
                "06:30",
                "07:00",
                "07:30",
                "08:00",
                "10:00",
                "11:00",
                "11:30",
                "12:00",
                "12:30",
                "13:00",
                "13:30",
                "15:00",
                "16:00",
                "17:30",
                "18:00",
                "19:00",
                "20:00"
            ]
        }
    ]
}

=== ernadosmic/brcko_bus/assets/schedules/line_10B.json
{
    "$schema": "./bus_schema.json",
    "name": "Bijela Škola - Tesla (povratak)",
    "line_number": "10B",
    "services": 3,
    "regular_services": [
        4,
        5,
        6
    ],
    "irregular_services": [],
    "regular_explanation": "Polasci pod brojevima 4, 5, 6 saobraćaju svakodnevno",
    "irregular_explanation": "",
    "stops": [
        {
            "name": "BIJELA ŠKOLA",
            "times": [
                "11:40",
                "14:30",
                "20:30"
            ]
        },
        {
            "name": "Bijela Dom",
            "times": [
                "11:39",
                "14:29",
                "20:29"
            ]
        },
        {
            "name": "Dubrave 'R'",
            "times": [
                "11:35",
                "14:25",
                "20:25"
            ]
        },
        {
            "name": "Dubrave Škola",
            "times": [
                "11:33",
                "14:23",
                "20:23"
            ]
        },
        {
            "name": "Dubrave 'R'",
            "times": [
                "11:30",
                "14:20",
                "20:20"
            ]
        },
        {
            "name": "Bijela Dom",
            "times": [
                "11:28",
                "14:18",
                "20:18"
            ]
        },
        {
            "name": "G. Skakava Škola",
            "times": [
                "11:24",
                "14:14",
                "20:14"
            ]
        },
        {
            "name": "G. Skakava",
            "times": [
                "11:24",
                "14:14",
                "20:14"
            ]
        },
        {
            "name": "Stjepkovica 'R'",
            "times": [
                "11:23",
                "14:13",
                "20:13"
            ]
        },
        {
            "name": "Prijedor Crkva",
            "times": [
                "11:22",
                "14:12",
                "20:12"
            ]
        },
        {
            "name": "Seonjaci 'R'",
            "times": [
                "11:20",
                "14:10",
                "20:10"
            ]
        },
        {
            "name": "D. Skakava P.",
            "times": [
                "11:17",
                "14:07",
                "20:07"
            ]
        },
        {
            "name": "D. Skakava Dom",
            "times": [
                "11:16",
                "14:06",
                "20:06"
            ]
        },
        {
            "name": "Bosutka 'R'",
            "times": [
                "11:14",
                "14:04",
                "20:04"
            ]
        },
        {
            "name": "Marićani",
            "times": [
                "11:12",
                "14:02",
                "20:02"
            ]
        },
        {
            "name": "Poljaci Škola",
            "times": [
                "11:09",
                "13:59",
                "19:59"
            ]
        },
        {
            "name": "Poljaci 'R'",
            "times": [
                "11:08",
                "13:58",
                "19:58"
            ]
        },
        {
            "name": "Jagodnjak M.",
            "times": [
                "11:06",
                "13:56",
                "19:56"
            ]
        },
        {
            "name": "Jagodnjak",
            "times": [
                "11:05",
                "13:55",
                "19:55"
            ]
        },
        {
            "name": "Bašče 'R'",
            "times": [
                "11:03",
                "13:53",
                "19:53"
            ]
        },
        {
            "name": "Zešče",
            "times": [
                "11:00",
                "13:50",
                "19:50"
            ]
        },
        {
            "name": "Vukišić",
            "times": [
                "10:58",
                "13:48",
                "19:48"
            ]
        },
        {
            "name": "Šukarice",
            "times": [
                "10:56",
                "13:46",
                "19:46"
            ]
        },
        {
            "name": "Ulice",
            "times": [
                "10:53",
                "13:43",
                "19:43"
            ]
        },
        {
            "name": "Jasenovac",
            "times": [
                "10:51",
                "13:41",
                "19:41"
            ]
        },
        {
            "name": "Barića Brdo",
            "times": [
                "10:48",
                "13:38",
                "19:38"
            ]
        },
        {
            "name": "Njivice",
            "times": [
                "10:47",
                "13:37",
                "19:37"
            ]
        },
        {
            "name": "Donji Rahić igralište",
            "times": [
                "10:45",
                "13:35",
                "19:35"
            ]
        },
        {
            "name": "Donji Rahić",
            "times": [
                "10:43",
                "13:33",
                "19:33"
            ]
        },
        {
            "name": "Grbavica I",
            "times": [
                "10:42",
                "13:32",
                "19:32"
            ]
        },
        {
            "name": "Grbavica Dom",
            "times": [
                "10:41",
                "13:31",
                "19:31"
            ]
        },
        {
            "name": "Grbavica Škola",
            "times": [
                "10:40",
                "13:30",
                "19:30"
            ]
        },
        {
            "name": "Ulički Put",
            "times": [
                "10:39",
                "13:29",
                "19:29"
            ]
        },
        {
            "name": "Gluhakovac",
            "times": [
                "10:38",
                "13:28",
                "19:28"
            ]
        },
        {
            "name": "PSC",
            "times": [
                "10:36",
                "13:26",
                "19:26"
            ]
        },
        {
            "name": "Bolnica",
            "times": [
                "10:35",
                "13:25",
                "19:25"
            ]
        },
        {
            "name": "Dom Zdravlja",
            "times": [
                "10:34",
                "13:24",
                "19:24"
            ]
        },
        {
            "name": "Kolobara",
            "times": [
                "10:33",
                "13:23",
                "19:23"
            ]
        },
        {
            "name": "Centar",
            "times": [
                "10:32",
                "13:22",
                "19:22"
            ]
        },
        {
            "name": "Vet. Stanica",
            "times": [
                "10:32",
                "13:22",
                "19:22"
            ]
        },
        {
            "name": "TESLA",
            "times": [
                "10:30",
                "13:20",
                "19:20"
            ]
        }
    ]
}

=== ernadosmic/brcko_bus/assets/schedules/line_12A.json
{
    "$schema": "./bus_schema.json",
    "name": "Tesla - Čerik Bor",
    "line_number": "12a",
    "services": 1,
    "regular_services": [
        1
    ],
    "irregular_services": [],
    "regular_explanation": "Polasci pod brojevima 1 saobraćaju svakodnevno",
    "irregular_explanation": "",
    "stops": [
        {
            "name": "TESLA",
            "times": [
                "10:10"
            ]
        },
        {
            "name": "Vet. Stanica",
            "times": [
                "10:11"
            ]
        },
        {
            "name": "Centar",
            "times": [
                "10:14"
            ]
        },
        {
            "name": "Kolobara",
            "times": [
                "10:16"
            ]
        },
        {
            "name": "Dom Zdravlja",
            "times": [
                "10:17"
            ]
        },
        {
            "name": "Meraje",
            "times": [
                "10:18"
            ]
        },
        {
            "name": "Izbor",
            "times": [
                "10:19"
            ]
        },
        {
            "name": "Suljagića Sokak",
            "times": [
                "10:20"
            ]
        },
        {
            "name": "Šadrvan",
            "times": [
                "10:21"
            ]
        },
        {
            "name": "Brod Škola",
            "times": [
                "10:25"
            ]
        },
        {
            "name": "Brod Spomenik",
            "times": [
                "10:27"
            ]
        },
        {
            "name": "Lukavac raskrs.",
            "times": [
                "10:32"
            ]
        },
        {
            "name": "Bukvik",
            "times": [
                "10:35"
            ]
        },
        {
            "name": "Bukvik ž.stan. \"R\"",
            "times": [
                "10:40"
            ]
        },
        {
            "name": "D.Škakava ras.",
            "times": [
                "10:45"
            ]
        },
        {
            "name": "Seonjaci",
            "times": [
                "10:50"
            ]
        },
        {
            "name": "Dubrave Škola",
            "times": [
                "10:55"
            ]
        },
        {
            "name": "Dubrave raskrs.",
            "times": [
                "11:00"
            ]
        },
        {
            "name": "Čerik Bor",
            "times": [
                "11:05"
            ]
        }
    ]
}

=== ernadosmic/brcko_bus/assets/schedules/line_5B.json
{
    "$schema": "./bus_schema.json",
    "name": "Bolnica - Satorovići",
    "line_number": "3",
    "services": 6,
    "regular_services": [
        7,
        8,
        9,
        10,
        11,
        12
    ],
    "irregular_services": [],
    "regular_explanation": "Polasci pod brojevima 7, 8, 9, 10, 11, 12 saobraćaju svakodnevno",
    "irregular_explanation": "",
    "stops": [
        {
            "name": "BOLNICA",
            "times": [
                "06:30",
                "11:00",
                "13:25",
                "16:30",
                "18:16",
                "19:26"
            ]
        },
        {
            "name": "DOM ZDRAVLJA",
            "times": [
                "06:31",
                "11:01",
                "13:26",
                "16:31",
                "18:17",
                "19:27"
            ]
        },
        {
            "name": "Kolobara",
            "times": [
                "06:32",
                "11:02",
                "13:27",
                "16:32",
                "18:18",
                "19:28"
            ]
        },
        {
            "name": "Robna kuća",
            "times": [
                "06:33",
                "11:03",
                "13:28",
                "16:33",
                "18:19",
                "19:29"
            ]
        },
        {
            "name": "Soliter",
            "times": [
                "06:34",
                "11:04",
                "13:29",
                "16:34",
                "18:20",
                "19:30"
            ]
        },
        {
            "name": "Grčica Crkva",
            "times": [
                "06:35",
                "11:05",
                "13:30",
                "16:35",
                "18:21",
                "19:31"
            ]
        },
        {
            "name": "Grčica I",
            "times": [
                "06:36",
                "11:06",
                "13:31",
                "16:36",
                "18:22",
                "19:32"
            ]
        },
        {
            "name": "Farma",
            "times": [
                "06:38",
                "11:08",
                "13:33",
                "16:38",
                "18:24",
                "19:34"
            ]
        },
        {
            "name": "Seljanka (Škola)",
            "times": [
                "06:39",
                "11:09",
                "13:34",
                "16:39",
                "18:25",
                "19:35"
            ]
        },
        {
            "name": "Potočari Crkva",
            "times": [
                "06:40",
                "11:10",
                "13:35",
                "16:40",
                "18:26",
                "19:36"
            ]
        },
        {
            "name": "Potočari I",
            "times": [
                "06:41",
                "11:11",
                "13:36",
                "16:41",
                "18:27",
                "19:37"
            ]
        },
        {
            "name": "Potočari II",
            "times": [
                "06:43",
                "11:13",
                "13:38",
                "16:43",
                "18:29",
                "19:39"
            ]
        },
        {
            "name": "Potočari III",
            "times": [
                "06:47",
                "11:17",
                "13:42",
                "16:47",
                "18:33",
                "19:43"
            ]
        },
        {
            "name": "Trešnjica",
            "times": [
                "06:51",
                "11:21",
                "13:46",
                "16:51",
                "18:37",
                "19:47"
            ]
        },
        {
            "name": "Dubravice D. (R)",
            "times": [
                "06:54",
                "11:24",
                "13:49",
                "16:54",
                "18:40",
                "19:50"
            ]
        },
        {
            "name": "Miladije",
            "times": [
                "06:58",
                "11:28",
                "13:53",
                "16:58",
                "18:44",
                "19:54"
            ]
        },
        {
            "name": "Dubravice II",
            "times": [
                "07:01",
                "11:31",
                "13:56",
                "17:01",
                "18:47",
                "19:57"
            ]
        },
        {
            "name": "Dubravice I",
            "times": [
                "07:03",
                "11:33",
                "13:58",
                "17:03",
                "18:49",
                "19:59"
            ]
        },
        {
            "name": "Satorovići I",
            "times": [
                "07:07",
                "11:37",
                "14:02",
                "17:07",
                "",
                "20:03"
            ]
        },
        {
            "name": "SATOROVIĆI",
            "times": [
                "07:09",
                "11:39",
                "14:04",
                "17:09",
                "",
                "20:05"
            ]
        }
    ]
}

=== ernadosmic/brcko_bus/assets/schedules/line_10A.json
{
    "$schema": "./bus_schema.json",
    "name": "Bijela Škola - Tesla",
    "line_number": "10",
    "services": 3,
    "regular_services": [
        1,
        2,
        3
    ],
    "irregular_services": [],
    "regular_explanation": "Polasci pod brojevima 1, 2, 3 saobraćaju svakodnevno",
    "irregular_explanation": "",
    "stops": [
        {
            "name": "BIJELA ŠKOLA",
            "times": [
                "05:35",
                "08:00",
                "11:35"
            ]
        },
        {
            "name": "Bijela Dom",
            "times": [
                "05:36",
                "08:01",
                "11:36"
            ]
        },
        {
            "name": "Dubrave (R)",
            "times": [
                "05:40",
                "08:05",
                "11:40"
            ]
        },
        {
            "name": "Dubrave Škola",
            "times": [
                "05:42",
                "08:07",
                "11:42"
            ]
        },
        {
            "name": "Dubrave (R)",
            "times": [
                "05:45",
                "08:10",
                "11:45"
            ]
        },
        {
            "name": "Bijela Dom",
            "times": [
                "05:47",
                "08:12",
                "11:47"
            ]
        },
        {
            "name": "G.Škakava Škola",
            "times": [
                "05:49",
                "08:14",
                "11:49"
            ]
        },
        {
            "name": "G.Škakava",
            "times": [
                "05:51",
                "08:16",
                "11:51"
            ]
        },
        {
            "name": "Stjepkovica (R)",
            "times": [
                "05:52",
                "08:17",
                "11:52"
            ]
        },
        {
            "name": "Prijedor Crkva",
            "times": [
                "05:53",
                "08:18",
                "11:53"
            ]
        },
        {
            "name": "Seonjaci (R)",
            "times": [
                "05:55",
                "08:20",
                "11:55"
            ]
        },
        {
            "name": "D.Škakava P.",
            "times": [
                "05:58",
                "08:23",
                "11:58"
            ]
        },
        {
            "name": "D.Škakava Dom",
            "times": [
                "05:59",
                "08:24",
                "11:59"
            ]
        },
        {
            "name": "Bosutka (R)",
            "times": [
                "06:01",
                "08:26",
                "12:01"
            ]
        },
        {
            "name": "Marićani",
            "times": [
                "06:03",
                "08:28",
                "12:03"
            ]
        },
        {
            "name": "Poljaci Škola",
            "times": [
                "06:06",
                "08:31",
                "12:06"
            ]
        },
        {
            "name": "Poljaci (R)",
            "times": [
                "06:07",
                "08:32",
                "12:07"
            ]
        },
        {
            "name": "Jagodnjak M.",
            "times": [
                "06:09",
                "08:34",
                "12:09"
            ]
        },
        {
            "name": "Jagodnjak",
            "times": [
                "06:10",
                "08:35",
                "12:10"
            ]
        },
        {
            "name": "Bašče (R)",
            "times": [
                "06:13",
                "08:38",
                "12:13"
            ]
        },
        {
            "name": "Žešće",
            "times": [
                "06:15",
                "08:40",
                "12:15"
            ]
        },
        {
            "name": "Vukšić",
            "times": [
                "06:17",
                "08:42",
                "12:17"
            ]
        },
        {
            "name": "Šukarice",
            "times": [
                "06:19",
                "08:44",
                "12:19"
            ]
        },
        {
            "name": "Ulice",
            "times": [
                "06:22",
                "08:47",
                "12:22"
            ]
        },
        {
            "name": "Jasenovac",
            "times": [
                "06:24",
                "08:49",
                "12:24"
            ]
        },
        {
            "name": "Barića Brdo",
            "times": [
                "06:27",
                "08:52",
                "12:27"
            ]
        },
        {
            "name": "Njivice",
            "times": [
                "06:28",
                "08:53",
                "12:28"
            ]
        },
        {
            "name": "Donji Rašić igrališ.",
            "times": [
                "06:30",
                "08:55",
                "12:30"
            ]
        },
        {
            "name": "Donji Rašić",
            "times": [
                "06:31",
                "08:56",
                "12:31"
            ]
        },
        {
            "name": "Grbavica I",
            "times": [
                "06:33",
                "08:58",
                "12:33"
            ]
        },
        {
            "name": "Grbavica Dom",
            "times": [
                "06:35",
                "09:00",
                "12:35"
            ]
        },
        {
            "name": "Grbavica Škola",
            "times": [
                "06:36",
                "09:01",
                "12:36"
            ]
        },
        {
            "name": "Ulički Put",
            "times": [
                "06:37",
                "09:02",
                "12:37"
            ]
        },
        {
            "name": "Gluhakovac",
            "times": [
                "06:38",
                "09:03",
                "12:38"
            ]
        },
        {
            "name": "PSC",
            "times": [
                "06:39",
                "09:04",
                "12:39"
            ]
        },
        {
            "name": "Bolnica",
            "times": [
                "06:40",
                "09:05",
                "12:40"
            ]
        },
        {
            "name": "Dom zdravlja",
            "times": [
                "06:41",
                "09:07",
                "12:42"
            ]
        },
        {
            "name": "Kolobara",
            "times": [
                "06:42",
                "09:08",
                "12:43"
            ]
        },
        {
            "name": "Centar",
            "times": [
                "06:43",
                "09:09",
                "12:44"
            ]
        },
        {
            "name": "Vet. Stanica",
            "times": [
                "06:45",
                "09:10",
                "12:45"
            ]
        },
        {
            "name": "TESLA",
            "times": [
                "06:45",
                "09:10",
                "12:45"
            ]
        }
    ]
}
